config/routes.rb
Rails.application.routes.draw do
  resources :reserves
  devise_for :users
  get 'home/index'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reserf.rb
class Reserf < ApplicationRecord
    belongs_to :user
end

app/models/reserve.rb
class Reserve < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reserves, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :confirmable,
         :database_authenticatable, 
         :registerable,
         :recoverable, 
         :rememberable,                   
         :trackable
         :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reserves_controller.rb
class ReservesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_reserf, only: %i[ show edit update destroy ]

  # GET /reserves or /reserves.json
  def index
    @reserves = Reserve.all
  end

  # GET /reserves/1 or /reserves/1.json
  def show
  end

  # GET /reserves/new
  def new
    @reserf = current_user.reserves.new
  end

  # GET /reserves/1/edit
  def edit
  end

  # POST /reserves or /reserves.json
  def create
    @reserf = current_user.reserves.new(reserf_params)

    respond_to do |format|
      if @reserf.save
        format.html { redirect_to reserf_url(@reserf), notice: "Reserve was successfully created." }
        format.json { render :show, status: :created, location: @reserf }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reserf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reserves/1 or /reserves/1.json
  def update
    respond_to do |format|
      if @reserf.update(reserf_params)
        format.html { redirect_to reserf_url(@reserf), notice: "Reserve was successfully updated." }
        format.json { render :show, status: :ok, location: @reserf }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reserf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reserves/1 or /reserves/1.json
  def destroy
    @reserf.destroy

    respond_to do |format|
      format.html { redirect_to reserves_url, notice: "Reserve was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reserf
      @reserf = Reserve.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reserf_params
      params.require(:reserf).permit(:name, :start_date, :termination_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reserves_helper.rb
module ReservesHelper
end

app/views/home/index.html.erb
<body class="layout-2">
 <div id="app">
    <div class="main-wrapper container">
      <div class="navbar-bg"></div>
      <nav class="navbar navbar-expand-lg main-navbar">
        <a href="/" class="navbar-brand sidebar-gone-hide">
          <%= image_tag("logo.png", alt:"logo", width:"50", class:"rounded-circle") %>
        </a>
        <div class="navbar-nav">
          <a href="/" class="nav-link sidebar-gone-show" data-toggle="sidebar"><i class="fas fa-bars"></i></a>
        </div>
        <div class="nav-collapse">
          <a class="sidebar-gone-show nav-collapse-toggle nav-link" href="#">
            <i class="fas fa-ellipsis-v"></i>
          </a>          
        </div>
        <form class="form-inline ml-auto">
          
        </form>
        <ul class="navbar-nav navbar-right">

          <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
            <div class="d-sm-none d-lg-inline-block">Seja Bem-Vindo</div></a>
            <div class="dropdown-menu dropdown-menu-right">
              <a href="/users/sign_up" class="dropdown-item has-icon">
                <i class="far fa-user"></i> Criar Conta
              </a>
              <a href="/reserves" class="dropdown-item has-icon">
                <i class="fas fa-bolt"></i> Entrar
              </a>
            </div>
          </li>
        </ul>
      </nav>

     

      <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          

          <div class="section-body">
            <h2 class="section-title">Seja bem-Vindo a Sala de Reuniões</h2>
            <div class="card">
              <div class="card-header">
                <h4>Sala de Reunião</h4>
              </div>
              <div class="card-body">
                <h6>Esta é uma aplicação teste para simular um ambiente de reservas de salas de reunião! Seja muito bem-vindo. 
                <br>No canto superior
                direito se encontra os links para se cadastrar e/ou logar, fique a vontade</h6>
              </div>
            </div>
          </div>
        </section>
      </div>
      <footer class="main-footer">
        <div class="footer-left">
          Copyright &copy; 2022 <div class="bullet"></div> Desenhado Por <a href="https://github.com/fabioNog/scheduleroom" target="_blank">Fabio Nogueira do Carmo</a>
        </div>      
      </footer>
    </div>
  </div>
  </body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
    <title>Login &mdash; ScheduleRoom</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    

      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
            

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js" integrity="sha512-l7jogMOI6ZWZJEY7lREjFdQum46y2+kpp/mnbJx7O+izymO9eGjL6Y4o7cEJNBdouhVHpti2Wd79Q6aIjPwxtQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
 

  </body>
</html>

app/views/reserves/_form.html.erb
<%= form_with(model: reserf) do |form| %>
  <% if reserf.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(reserf.errors.count, "error") %> prohibited this reserf from being saved:</h2>

      <ul>
        <% reserf.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.date_field :start_date %>
  </div>

  <div>
    <%= form.label :termination_date, style: "display: block" %>
    <%= form.date_field :termination_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/reserves/_reserve.html.erb
<div id="<%= dom_id reserve %>">
  <p>
    <strong>Name:</strong>
    <%= reserve.name %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= reserve.start_date %>
  </p>

  <p>
    <strong>Termination date:</strong>
    <%= reserve.termination_date %>
  </p>

</div>

app/views/reserves/edit.html.erb
<h1>Editing reserve</h1>

<%= render "form", reserf: @reserf %>

<br>

<div>
  <%= link_to "Show this reserve", @reserf %> |
  <%= link_to "Back to reserves", reserves_path %>
</div>

app/views/reserves/index.html.erb
  <div id="app">
    <div class="main-wrapper">
      <div class="navbar-bg"></div>
      <nav class="navbar navbar-expand-lg main-navbar">
        <form class="form-inline mr-auto">
          <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
            <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i class="fas fa-search"></i></a></li>
          </ul>
        </form>
        <ul class="navbar-nav navbar-right">
          <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
            <div class="d-sm-none d-lg-inline-block">Hi, Ujang Maman</div></a>
            <div class="dropdown-menu dropdown-menu-right">
              <div class="dropdown-title">Logged in 5 min ago</div>
              <a href="features-profile.html" class="dropdown-item has-icon">
                <i class="far fa-user"></i> Profile
              </a>
              <a href="features-activities.html" class="dropdown-item has-icon">
                <i class="fas fa-bolt"></i> Activities
              </a>
              <a href="features-settings.html" class="dropdown-item has-icon">
                <i class="fas fa-cog"></i> Settings
              </a>
              <div class="dropdown-divider"></div>
              <a href="#" class="dropdown-item has-icon text-danger">
                <i class="fas fa-sign-out-alt"></i> Logout
              </a>
            </div>
          </li>
        </ul>
      </nav>
      <div class="main-sidebar">
        <aside id="sidebar-wrapper">
          <div class="sidebar-brand">
            <a href="index.html">Stisla</a>
          </div>
          <div class="sidebar-brand sidebar-brand-sm">
            <a href="index.html">St</a>
          </div>
          <ul class="sidebar-menu">
              <li class="menu-header">Dashboard</li>
              <li class="nav-item dropdown">
                <a href="#" class="nav-link has-dropdown"><i class="fas fa-fire"></i><span>Dashboard</span></a>
              </li>              
            </ul>

            <div class="mt-4 mb-4 p-3 hide-sidebar-mini">
            <%= link_to "Reservas de Salas", "/reserves", class:"btn btn-primary btn-lg btn-block btn-icon-split" %>
             
            </div>
        </aside>
      </div>

      <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>Calendário</h1>            
          </div>

          <div class="section-body">
            
            

            <div class="row">
              <div class="col-12">
                <div class="card">
                  <div class="card-header">
                    <h4>Calendário</h4>
                  </div>
                  <div class="card-body">
                    <div class="fc-overflow">
                      <div id="myEvent"></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
      <footer class="main-footer">
        <div class="footer-left">
          Copyright &copy; 2018 <div class="bullet"></div> Desenhado por <a href="https://nauval.in/">Fabio Nogueira</a>
        </div>
        <div class="footer-right">
          2.3.0
        </div>
      </footer>
    </div>
  </div>

app/views/reserves/new.html.erb
<h1>New reserve</h1>

<%= render "form", reserf: @reserf %>

<br>

<div>
  <%= link_to "Back to reserves", reserves_path %>
</div>

app/views/reserves/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @reserf %>

<div>
  <%= link_to "Edit this reserve", edit_reserf_path(@reserf) %> |
  <%= link_to "Back to reserves", reserves_path %>

  <%= button_to "Destroy this reserve", @reserf, method: :delete %>
</div>